### ISSUE TITLE
Attributes Assume []string value

### ISSUE THREAD

**Issue by guygrigsby** [splitio/go-client#101]
When an attribute value is set to a string, as in this [example](https://help.split.io/hc/en-us/articles/360020093652-Go-SDK#attribute-syntax), rather than []string value the following error occurs.

`ERROR - 2019/11/11 EqualToSetMatcher: Cannot type assert to []string`

**Comment by mredolatti** [comment]
Hi @guygrigsby, 
thank you very much for reaching out. We're sorry to hear you're having issues with our SDK.
It seems like your using a Set-based matcher, which expects a slice of items, and not a plain string.
Could you send us a code snippet and information on how you configured your split?
Feel free to contact  support@split.io with those details if you'd rather not make them public on this issue.

We apologize for any inconveniences caused.
Looking forward to hearing from you.
Regards,
Martin.

**Comment by guygrigsby** [comment]
Ahh. OK thanks. It seems I misunderstood how it worked. Got it now. Thank you.

**Comment by mredolatti** [comment]
I'm glad it's working now. Please do not hesitate to re-open if you're having any further issues, something's not working as expected, or you need further assistance.

Thank you,
Martin.
