### ISSUE TITLE
Split client using exorbitant amount of resources

### ISSUE THREAD

**Issue by tsholmes** [splitio/go-client#106]
<img width="835" alt="Screen Shot 2020-01-20 at 2 59 00 PM" src="https://user-images.githubusercontent.com/2865426/72762701-70642a80-3b95-11ea-9a08-f19b0ecdbecf.png">

The `SplitClient.Treatment` call seems to make a full deep copy of the split configuration on each call. This ends up being more than 50% of all allocations in our api server. This makes getting the treatment for a split more expensive than reading a thousand rows from bigtable (which is what the split is affecting).

**Comment by tsholmes** [comment]
The above chart is total size of allocations (~75%). This one is total number of allocations (~95%)
<img width="268" alt="Screen Shot 2020-01-20 at 3 07 36 PM" src="https://user-images.githubusercontent.com/2865426/72763017-a229c100-3b96-11ea-8ccd-962eb185ecfd.png">

**Comment by tsholmes** [comment]
Looking through the code, it looks like the DTO isn't actually written to at all by anything fetching it, so the deep copy seems unnecessary. You should be able to just swap the instance in the map on syncing splits from the server and use the one latest instance to calculate all the splits

**Comment by mredolatti** [comment]
Hi @tsholmes thanks for reaching out with such a comprehensive analysis. Sorry to hear you're having issues with our SDK. The deep-copy is a leftover from our initial release, when we weren't 100% settled on the immutability of split objects. We will remove suche logic and send this to our QA environment. 
We'll let you know as soon as we have a new release with such logic removed.
Thank you very much and our apologies for any inconveniences caused.
Martin.

**Comment by mredolatti** [comment]
Hi @tsholmes , we've sent a new version of the split SDK to our QA environment which fixes the issue you reported. If everything goes well, we'll make a release on monday.
Thank you very much for your patience, and once again, our apologies for the inconveniences caused.

Thanks,
Martin.

**Comment by mmelograno** [comment]
Hi @tsholmes, we've deployed split `5.1.3` version that fixes the issue that you reported.
Please let us know if you have any further issues or questions regarding our SDK.

I'll be closing this issue for now, but feel free to reopen if necessary.

Thank you once again for reaching out.
Matias.
