### ISSUE TITLE
Docs syntax error

### ISSUE THREAD

**Issue by devosnw** [splitio/go-client#112]
The example code in https://help.split.io/hc/en-us/articles/360020093652-Go-SDK#multiple-evaluations-at-once has a syntax error on line 9 (missing comma). I didn't know where to raise issues like this so thought I'd point it out here.

**Comment by mredolatti** [comment]
Hi @devosnw , you're right, we have a missing comma between `split` and `treatment`. We'll fix it now. 

Thank you very much for reaching out,
Martin.
