### ISSUE TITLE
Redis Connection Drop

### ISSUE THREAD

**Issue by josefld** [splitio/go-client#129]
Hi all! 
We are facing an issue using TreatmentsWithConfig, with the client configured as a redis consumer.
The thing is that sometimes we fail to retrieve Treatments and we are not sure about why. The solution to the problem for now, is to restart the application. So we suspect that the connection to redis is dropped, but we don't have logs or much information to sustain this.
I was wondering if there is a way to check the connection to the underlying redis before retrieving any treatment and in case of a dropped connection start a fresh one.

Thanks in advance.

**Comment by chillaq** [comment]
Hi @josefld, Could you enable SDK logging with Verbose option and share the logs?

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @josefld, I am following up on this issue, do you still require any assistance?

Thanks
Bilal

**Comment by josefld** [comment]
Hi sir! sorry for the late response. 
Thanks very much for your concern, but unfortunately I can't share the logs, since I don't have one (environment issue) . 
I did a workaround injecting a custom logger and searching for any redis related message, but is not de proper answer for me.
Maybe I'm not looking at the hole picture but, for me, it would be ideal to handle errors like that in the functions that make the request to redis like TreatmentsWithConfig or some other.
that make sense to you?
Regards.-

**Comment by chillaq** [comment]
Hi Jose,

We designed the getTreatmentsWithConfig function to never error out or raise an exception to minimize the impact on customer code, instead we return "control" as the treatment and advise to view the log files for any errors.

You can setup the SDK logging for INFO which will capture Error as well in case redis connection has an issue, checkout this link for how to setup the log: https://help.split.io/hc/en-us/articles/360020093652-Go-SDK#logging

If you have a monitoring script for redis, that can help as well, let me know if you have any questions.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Jose, I am following up on this issue, do you still require any assistance?

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Jose, I am closing out this issue. If there is still an open issue or if we can be of further assistance on this topic, feel free to re-open it.

Thanks
Bilal
