### ISSUE TITLE
Panic while fetching segments

### ISSUE THREAD

**Issue by nachogoca** [splitio/go-client#135]
```
error 	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x637532]
ERROR
goroutine 21399 [running]:
compress/gzip.(*Reader).Close(0x0, 0xf31ca0, 0xc0fc5a9c00)
 	/usr/local/go/src/compress/gzip/gunzip.go:292 +0x22
panic(0xc620c0, 0x154b780)
 	/usr/local/go/src/runtime/panic.go:513 +0x1b9
io/ioutil.readAll.func1(0xc046d93b60)
 	/usr/local/go/src/io/ioutil/ioutil.go:30 +0x105
 panic(0xc620c0, 0x154b780)
 	/usr/local/go/src/runtime/panic.go:513 +0x1b9
 compress/gzip.(*Reader).Read(0x0, 0xc0ba476400, 0x200, 0x200, 0x200, 0x200, 0xc0ba476400)
 	/usr/local/go/src/compress/gzip/gunzip.go:247 +0x37
 bytes.(*Buffer).ReadFrom(0xc14b392ee0, 0x7ffb57b05500, 0x0, 0xc000508000, 0xc6f4a0, 0xcb28e0)
 	/usr/local/go/src/bytes/buffer.go:206 +0xb4
 io/ioutil.readAll(0x7ffb57b05500, 0x0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
 	/usr/local/go/src/io/ioutil/ioutil.go:36 +0xb5
 io/ioutil.ReadAll(0x7ffb57b05500, 0x0, 0x0, 0x7ffb57b05500, 0x0, 0xc0c1c38db0, 0x2b)
 	/usr/local/go/src/io/ioutil/ioutil.go:45 +0x3e
bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/service/api.(*HTTPClient).Get(0xc021cc65f0, 0xc096d7fc20, 0x41, 0x0, 0x0, 0x0, 0x0, 0x0)
 	/go/src/bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/service/api/client.go:103 +0x76e
bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/service/api.(*httpFetcherBase).fetchRaw(0xc037b9dbc0, 0xc0c1c38d80, 0x2d, 0x172114f8eb9, 0xc0c1c38d80, 0x2d, 0xc000038f70, 0xc000038f00, 0xc046d93e48)
 	/go/src/bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/service/api/http_fetchers.go:27 +0xee
 bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/service/api.(*HTTPSegmentFetcher).Fetch(0xc037b9dbc0, 0xc02fe96660, 0x1d, 0x172114f8eb9, 0x172114f8eb9, 0x0, 0x0)
 	/go/src/bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/service/api/http_fetchers.go:110 +0x125
 bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/tasks.updateSegment(0xf31120, 0xc037b9dbc0, 0x7ffb57aa82e8, 0xc037b9db40, 0xc02fe96660, 0x1d, 0x0, 0x0, 0x0)
 	/go/src/bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/tasks/segmentsync.go:22 +0x9f
 bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/tasks.NewFetchSegmentsTask.func1.1(0xc0425ae730, 0xf31120, 0xc037b9dbc0, 0x7ffb57aa82e8, 0xc037b9db40, 0xc037ba3280, 0xc02fe96660, 0x1d)
 	/go/src/bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/tasks/segmentsync.go:135 +0x9b
 created by bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/tasks.NewFetchSegmentsTask.func1
 	/go/src/bitbucket.org/companyrepo/companyservice/vendor/github.com/splitio/go-client/splitio/tasks/segmentsync.go:130 +0x214 
```
I have not been able to reproduce this issue in a dev environment. The only pattern I see is that this issue happens when our microservice scales up. So probably when a new instance is rolled out, maybe it's a lot of data to be fetched and the segment fetching process fails.

My configuration is the default, so it defaults to in-memory.
`20` is the value given to the BlockUntilReady function.

Version:
  digest = "1:5e8048ff5760a83c2ff7fbe1eac3cae053ea0cb0de1ba9f2c51b3ba7ac3fff7b"
  name = "github.com/splitio/go-client"
  version = "5.1.3"

**Comment by chillaq** [comment]
Thanks @nachogoca checking with the team.

**Comment by chillaq** [comment]
Hi @nachogoca could you provide which workspace and environment you are using, I can check the segments in that environment and try to repro on my side.

Thanks
Bilal

**Comment by nachogoca** [comment]
Thanks for the quick response @chillaq 

This is the URL I use to access my splits: https://app.split.io/org/f9f34a80-5a52-11e9-a716-12a5cc2af8fe/ws/cb2d7af0-6de3-11e9-8af6-0a1c02136776/environments/cb33bc80-6de3-11e9-8af6-0a1c02136776

I think there are some uuids that should allow you to identify my company org, workspace and environment?

**Comment by chillaq** [comment]
Hi @nachogoca, I tried to repro the issue using 80 segments each with 10k records, ran Go SDK 6.0.1 and did not see any memory errors, I removed and added keys randomly and the SDK was updating the cache without issues.

Is it possible for you to upgrade to latest version (SDK 6.0.1)? This is the version we support going forward.

Thanks
Bilal

**Comment by mredolatti** [comment]
Sorry for hijacking this, but we have an upcoming release (most likely tomorrow) which among other things, will prevent that panic. The request will still fail if this scenario happens again, since it seems to be caused by an invalid gzip header in the response body, but it should not cause a panic. We'll let you know as soon as it's out.

Thank you guys,
Martin.

**Comment by nachogoca** [comment]
Thank you both! Then, I'll be waiting for that new release :smile:

**Comment by mredolatti** [comment]
Hi @nachogoca `v6.0.2` is out which should handle this scenarios better.
Please let me know if after updating you're still having issues.

Regards,
Martin.
