### ISSUE TITLE
Error fetching split changes  Get "https://sdk.split.io/api/splitChanges?since=1667935351266"

### ISSUE THREAD

**Issue by shanepisko** [splitio/go-client#172]
we occasionally see this error and it prevents our initialized client from getting changes and seems to only be solvable by restarting the app. Is there any insight into how to catch this and manually reinitialize the client? I do not see any way to hook into this occurrence. I would expect the client would fail if it cannot fetch changes. Or are we supposed to handle reinitialization if "control" is being returned for all of our treatments?

**Comment by Tim020** [comment]
Hi Shane,

This error should be transient and the SDK will retry such operations, and should not require the entire application to be restarted. Do you have debug logging enabled on the SDK which would allow us to look into this?

Tim

**Comment by shanepisko** [comment]
@Tim020 currently only the default error log level, what would be suggested log level to enable? From what we have seen, we do not see retry happening since the values of treatment calls for a key which has been updated in split is not being reflected in our query.

**Comment by Tim020** [comment]
@shanepisko I would suggest going with debug logging for trying to analyse issues!

To clarify, are you seeing that when you call `getTreatment`, the treatment returned is not the same as you would expect?

**Comment by Tim020** [comment]
Hi @shanepisko just wondering if you still need any help here?

**Comment by agustinona** [comment]
Hi @shanepisko ,

Are you still facing this issue? Could you share more info about the error itself (ideally SDK debug logs)?

**Comment by agustinona** [comment]
@shanepisko ping :)
